#! /bin/sh

#
# Compile script for Virtual Jaguar GCC/SDL Portable Jaguar Emulator
# This obviates the need for separate Makefiles for every OS architecture
# under the sun...
#
# by James L. Hammons
#
# If you have any parameters that you want to pass through to make, then
# simply add them to the 'compile' command line as if 'compile' were make.
#

echo
echo -n "*** Checking compilation environment... "

# Check for SDL

if [ "`which sdl-config`" = "" ]; then

	echo
	echo
	echo "It seems that you don't have the SDL development libraries installed. If you"
	echo "have installed them, make sure that the sdl-config file is somewhere in your"
	echo "path and is executable."

	exit 1

fi

echo -n "OK"

echo
echo -n "*** Compiling Virtual Jaguar for "

# Check the OS type...

if [ "$OSTYPE" = "msys" ]; then

	echo -n Win32 on MinGW

	SYSTYPE=__GCCWIN32__
	EXESUFFIX=.exe
	GLLIB=-lopengl32
	ICON=vj-ico.o
	SDLLIBTYPE=--libs
#This doesn't seem to make a difference on Win32...
#	SDLLIBTYPE=--static-libs

elif [ "$OSTYPE" = "darwin7.0" ] || [ "$OSTYPE" = "darwin" ]; then

	echo -n Mac OS X

	SYSTYPE=__GCCUNIX__ -D_OSX_
	EXESUFFIX=
	GLLIB=
	ICON=
	SDLLIBTYPE=--static-libs

else # *nix

	echo -n generic Unix/Linux

	SYSTYPE=__GCCUNIX__
	EXESUFFIX=
	GLLIB=-lGL
	ICON=
	SDLLIBTYPE=--libs

fi

echo ...
echo

export SYSTYPE EXESUFFIX GLLIB ICON SDLLIBTYPE

# Yes, you can pass through parameters to make...

make $@

if [ $? -eq 0 ]; then

	echo
	echo "*** Looks like it compiled OK... Give it a whirl!"
	echo

fi
