#!/bin/bash
#
# Short script to do cross compilation with MXE on Linux
#
# by James Hammons
# (C) 2012 Underground Software
#
echo "Cross compiling for Win32..."
export PATH=/opt/mxe/usr/bin:$PATH
rm makefile-qt
make CROSS=i686-pc-mingw32-
#rel=`svn info | grep Revision | cut -f 2 -d ' '`
rel=`git log -1 --pretty=format:%ci | cut -d ' ' -f 1 | tr -d -`
cd release && upx -9v virtualjaguar.exe && zip -9v vj-$rel.zip virtualjaguar.exe
